node {
 try  {
 notify('Job Started') 

     
  stage('Git-Checkout') {
   git 'https://github.com/adityashankar48711/QAEnvironment.git'
  }
	 
 def project_path="devops/"
 
 dir(project_path) {
    
 
	 
	 stage('Jfrog Artifactory download'){
    def server= Artifactory.server 'Artifactory'
    def downloadSpec = """{
    "files": [
    {
      "pattern": "petclinic/*.war",
      "target": "/home/mtadminnuvepro/artifacts/"
      
    }
    ]
    }"""
    server.download(downloadSpec)
   
}
     
   stage('Docker-Stage-Deployment') {
   sh label: 'DOCKER DEPLOYMENT', script: 'docker-compose up -d --build'
  }
	 


}

notify('Job Completed')   
} catch (err) {
  notify("Error ${err}")
  currentBuild.result = 'FAILURE'
}
}

def notify(status){
    emailext (
	to: "aditya.shankar@mindtree.com",
	subject: "${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
	 body: """<p>${status}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
	<p>Check console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
		)
	}
